re-work lite clients into 'Browsers & Mobile'
ipfs-shipyard/ipfs-thing-2022 pull request #34
Opened 2022-06-21 02:10 UTC by b5

Hey all, I've restructured the "Lite Clients" track to include browsers and provide a goal for this half-day workshop. I'd love your feedback!

@RangerMauve & @matheus23, I'm asking for both of you (or someone from your org) to give lightning talks to help support this goal of moving the ball forward on IPFS in weird places. I'll wait for both of your feedback & approval before merging.

I'm also seeking feedback from folks I'd love to have attend:
@achingbrain
@autonome
@ikreymer
@lidel
@dignifiedquire

My first request for feedback: who else should we be trying to get to attend?

closes #31

2022-06-21 08:23 UTC, matheus23 commented
I can commit to preparing a lightning talk :+1:

2022-06-24 14:55 UTC, autonome commented
* add a "DIY content routing" session using Reframe for a "lite client" approach to DHT alternatives

2022-06-24 18:47 UTC, RangerMauve requested changes
Yeah, I'd love to talk about Agregore's approach to URLs and `fetch()`. 😁 One thing I'd like to focus is some existing `ipfs://` and `ipns://` URL protocol handlers in stuff like Brave and Capyloon and how they can become more powerful with the addition of `PUT/POST/DELETE` verbs.

2022-06-24 18:47 UTC, RangerMauve commented on events/d_3_browsers_and_mobile.toml
> +description="this talk is unconfirmed"
```suggestion
description="This talk will look at Peer to Peer URLs and how they can be used in tandem with HTTP-like APIs within webapps using custom protocol handlers."
```

2022-06-28 14:49 UTC, merged